### ISSUE TITLE
maddpg训练问题

### ISSUE THREAD

**Issue by 2568754202** [StepNeverStop/RLs#22]
我用maddpg训练一个unity应用，配置了多个大脑，输出action都是连续的，但是运行一开始就报错，list has no attributes  is_continuous。

**Comment by BlueFisher** [comment]
@2568754202 we'll check and work on it.

**Comment by 2568754202** [comment]
I found the problem , the behavior name must like '2#Brain'. But there is a new bug that too many values to unpack (expected 5).

**Comment by 2568754202** [comment]
s, visual_s, _, _, _ = env.reset()
s, visual_s = map(data_change_func, [s, visual_s])
we must set reset_config={.....}
how to set?

**Comment by StepNeverStop** [comment]
@2568754202 This repo is now under deep reconstruction, and maddpg has lots of details out-of-date. We highly recommend you not use this repo to training multi-agent environments for now.

**Comment by 2568754202** [comment]
Thank you! But there is only a Multi-Agent training algorithms in your RLS.

**Comment by StepNeverStop** [comment]
@2568754202 yes, my main research direction is single-agent RL. So the progress of multi-agents algorithms is slow and priority is low. But I'll reconstruct/optimize MADDPG asap. :)

**Comment by 2568754202** [comment]
Your work is great! Thank you so much
