### ISSUE TITLE
Hello. I want to know how to use RLs into unity3d-mlagent.

### ISSUE THREAD

**Issue by strikeman1** [StepNeverStop/RLs#23]
I have read your project,but i do not know how to use in mlagent.please teach me,thanks.

**Comment by StepNeverStop** [comment]
1. follow the docs in official released ml-agents to build your custom training environment.
2. type `python run.py -u` to invoke the default PPO algorithm to interact with Unity Editor
3. press Start button in Unity Editor to establish a connection for your algorithm and environment.

**Comment by strikeman1** [comment]
ok,i will have a try,thank you

**Comment by strikeman1** [comment]
do you have wechat ,can i got it,it will communicate  with you more convenient

**Comment by StepNeverStop** [comment]
sorry, you could contact me by e-mail: keavnn.wjs@gmail.com if you need more help.

**Comment by strikeman1** [comment]
ok，thank you

**Comment by strikeman1** [comment]
![问题](https://user-images.githubusercontent.com/59919313/103152935-a9eede00-47c7-11eb-944c-0804920ac8fe.JPG)
why my training has this problem,I use this command-"python run.py -u -a ppo -n run_with_unity" and start unity.

**Comment by StepNeverStop** [comment]
@strikeman1 Sorry, I totally have no idea about your problem encountered, there is no package named "naming" that is used in this repo. Maybe you could try `pip install -e .[unity]` and then start your training, or you could try the code in branch `dev`.

BTW, if you have any questions, plz reopen this issue or create a new one so as I could get it timely.

**Comment by strikeman1** [comment]
sry,I know,thx,I have a try

**Comment by strikeman1** [comment]
and I  want to ask you other question,this project use GPU? I have GPU installed,but it remain have this question
![new question](https://user-images.githubusercontent.com/59919313/103184537-9fc9fe00-48f3-11eb-9ad7-6e0fb4358094.png)
