### ISSUE TITLE
and I  want to ask you other question,this project use GPU? I have GPU installed,but it remain have this question

### ISSUE THREAD

**Issue by strikeman1** [StepNeverStop/RLs#24]
and I  want to ask you other question,this project use GPU? I have GPU installed,but it remain have this question
![new question](https://user-images.githubusercontent.com/59919313/103184537-9fc9fe00-48f3-11eb-9ad7-6e0fb4358094.png)

_Originally posted by @strikeman1 in https://github.com/StepNeverStop/RLs/issues/23#issuecomment-751547720_

**Comment by StepNeverStop** [comment]
@strikeman1 this problem is no matter with your GPU. You have written a wrong starting command with incorrected format.

THERE is no more space between `3DBall` and `run_with_unity`.

Try `python run.py -u -a ppo -n test` and I think you should learn something about `docopt`.

**Comment by strikeman1** [comment]
ok,thx

**Comment by strikeman1** [comment]
I'm sorry to disturb you，if I use this project to train mlagent do I need to nstallation  mlagent environment？

**Comment by StepNeverStop** [comment]
@strikeman1 you just need to run `pip install -e .[unity]` and download ml-agents realease 12 to build your training environment. Plz make sure your RLs is up-to-date.

**Comment by strikeman1** [comment]
can I train the example in mlagent use this project?

**Comment by StepNeverStop** [comment]
yes.

**Comment by strikeman1** [comment]
I use mlagent0.21.0,is it ok ？

**Comment by StepNeverStop** [comment]
follow this [guide](https://github.com/Unity-Technologies/ml-agents/releases/tag/release_12).

**Comment by StepNeverStop** [comment]
fell free to reopen this issue.

**Comment by strikeman1** [comment]
ok，thx，it helped me a lot.
