### ISSUE TITLE
Cite Activations

### ISSUE THREAD

**Issue by digantamisra98** [StepNeverStop/RLs#4]
Hi. 
Awesome work. I am relatively new to RL in general. But this is a real good resource. I would really appreciate if you could cite my activation function "Mish" and same for Swish. Would help users to backtrack to the origin papers of those algorithms. 
The original repository for Mish - https://github.com/digantamisra98/Mish
The Readme contains the link to the arXiv paper as well. 
If you'd like to cite the paper instead, the link is - https://arxiv.org/abs/1908.08681
Thank You!

**Comment by StepNeverStop** [comment]
Thank you for your remaining, I'll cite your project and paper as soon as possible(maybe tonight). Thank you very much for your great work!

**Comment by digantamisra98** [comment]
Much Appreciated. Keep up the amazing work. Thanks again!
