### ISSUE TITLE
sac 在LunarLander-v2上的使用有问题，

### ISSUE THREAD

**Issue by wkhawyha** [StepNeverStop/RLs#44]

**Comment by StepNeverStop** [comment]
This problem is correlated with gradient backward and I've fixed that at commit [ab5fffc](https://github.com/StepNeverStop/RLs/commit/ab5fffcc2e06214dc75a850aeaf06aa12c5dc1f9)

**Comment by StepNeverStop** [comment]
feel free to reopen this.
