### ISSUE TITLE
运行python run.py -p unity -a ppo -n run_with_unity时报错

### ISSUE THREAD

**Issue by SKT647** [StepNeverStop/RLs#46]
您好，我输入 python run.py -p unity -a ppo -n run_with_unity  ，运行Unity后遇到了这个问题：name '_outs' is not defined，多次重新安装之后依然还是这样。请问应该如何解决呢，希望得到您的指点，谢谢！
![problem](https://user-images.githubusercontent.com/35840795/129299803-6c300dda-485e-4111-ba11-fad5b3135d7d.png)

**Comment by StepNeverStop** [comment]
@SKT647 你先下载`dev`分支下的代码试一下。

另外，本仓库正在进行代码重构，些许bug暂不维护，之后将维护重构后的训练框架。

**Comment by SKT647** [comment]
好的，谢谢您



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月13日(周五) 中午11:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [StepNeverStop/RLs] 运行python run.py -p unity -a ppo -n run_with_unity时报错 (#46)




 
@SKT647 你先下载dev分支下的代码试一下。
 
另外，本仓库正在进行代码重构，些许bug暂不维护，之后将维护重构后的训练框架。
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SKT647** [comment]
您好，我进行了多次重新安装与尝试，用dev分支下的代码同样也遇到了上述问题，但仅在mlagents release_18的3DBall环境中跑成功了（ppo sac等），请问这有可能是使用vpn安装库导致的bug吗

**Comment by StepNeverStop** [comment]
@SKT647 不是，是神经网络定义部分有书写bug，目前正在重构代码。重构后的训练框架会修复诸多已知bug。

**Comment by SKT647** [comment]
> @SKT647 不是，是神经网络定义部分有书写bug，目前正在重构代码。重构后的训练框架会修复诸多已知bug。

好的 谢谢

**Comment by StepNeverStop** [comment]
the issue has been fixed in the new verion.
feel free to reopen it.
