### ISSUE TITLE
fix  function update_config in run.py

### ISSUE THREAD

**Issue by kmakeev** [StepNeverStop/RLs#7]
Must be:
def update_config(config, file):
    _config = sth.load_config(file)
    try:
        for key in _config:
            config[key] = _config[key]
    except Exception as e:
        print(e)
        sys.exit()
    return config

**Comment by StepNeverStop** [comment]
Hi,
Thx for your correction.I wasn't aware of the mistake because there was no error in running this sentence.
I've fix this, thank you very much.
next time maybe you can submit a PR. so that I can merge it.

**Comment by kmakeev** [comment]
Ok!

**Comment by StepNeverStop** [comment]
Feel free to reopen this issue if still have questions.
